version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout # check out source code to working directory
      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      - run: mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies # gets the project dependencies
      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      - run: mvn compile
      - run: mvn test
      - store_test_results:
          path: target/surefire-reports
      - run: mvn package
